spring:
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
    show-sql: true
  profiles:
    active: dev

logging:
  level:
    root: info

application:
  name: LinkShorter API
  description: This is a URL shorter like bit.ly
  version: 0.0.1-SNAPSHOT
  license: MIT License
  License-url: https://github.com/GLinBoy/linkshorter/blob/master/LICENSE.md
  github-url: https://github.com/GLinBoy/linkshorter
  config:
    codeSize: 6
    hashAlgorithm: SHA-1
