CREATE TABLE URL (
	ID BIGINT auto_increment NOT NULL,
	CODE varchar(10) NOT NULL,
	ORIGINAL varchar(255) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
	UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
	CONSTRAINT URL_PK PRIMARY KEY (ID),
	CONSTRAINT UNQ_CODE UNIQUE (CODE),
	CONSTRAINT UNQ_ORGINAL UNIQUE (ORIGINAL)
);

CREATE INDEX INDX_CODE
ON URL (CODE);

CREATE INDEX INDX_ORGINAL
ON URL (ORIGINAL);